meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv: fix spacing
  - Add newlines where appropriate.
  - Replace tabs with four spaces for consistency.
  - Add missing indentations

Signed-off-by: Adam Duskett <aduskett@gmail.com>

diff --git a/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv b/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
--- a/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
+++ b/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
@@ -4,9 +4,9 @@ LABELCHARS="AB"
 get_bootpart() {
     local current_slot=`nvbootctrl get-current-slot 2>/dev/null || tegra-boot-control --current-slot 2>/dev/null`
     if [ -z "$current_slot" ]; then
-	echo "ERR: could not identify current boot slot" >&2
-	echo "UNKNOWN"
-	return
+        echo "ERR: could not identify current boot slot" >&2
+        echo "UNKNOWN"
+        return
     fi
     local cfglbl="\"RootfsPart${LABELCHARS:$current_slot:1}\""
     local devnam=`grep -h "$cfglbl:" /etc/mender/mender.conf /var/lib/mender/mender.conf | tr -d '" ,' | grep -o '[0-9]\+$'`
@@ -22,11 +22,13 @@ if [ "$1" = "-n" ]; then
         exit 1
     fi
 fi
+
 if [ -z "$1" ]; then
     bootpart=`get_bootpart`
     echo "mender_boot_part=$bootpart"
     exit 0
 fi
+
 while [ -n "$1" ]; do
     case "$1" in
         mender_boot_part)
